### ISSUE TITLE
一点目前使用遇到的问题

### ISSUE THREAD

**Issue by FujinomiyaNeko981213** [TwooSix/Alist-MikananiRss#2]
before
    def filt_entries(self, feed: feedparser.FeedParserDict) -> bool:
        """Filter feed entries using regex"""
        match_result = True
        for entry in feed.entries:
            for pattern in self.filter:
                match_result = match_result and re.search(pattern, entry.title)
            if match_result:
                yield entry
after
    def filt_entries(self, feed: feedparser.FeedParserDict) -> bool:
        """Filter feed entries using regex"""
        for entry in feed.entries:
            match_result = True
            for pattern in self.filter:
                match_result = match_result and re.search(pattern, entry.title)
            if match_result:
                yield entry

同时还遇到貌似是发送请求过多拒绝访问
HTTPSConnectionPool(host='mikanani.me', port=443): Max retries exceeded with url: /Home/Episode/fd4cf64f059b12f76579f92a842db5eadfaf7424 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))，如果能帮忙解决一下是最好了，THX

**Comment by TwooSix** [comment]
1. 对于你给出的代码我不太能完全理解你具体想达成的效果，能给一点更具体的解释吗？
2. 拒绝访问的代码是403，这个提示只是ssl握手失败，不知道这个问题是偶发还是常态？是否有正常运行成功的时候？导致这个问题的原因可以有很多，大概率是自身网络环境问题。你是不是配置了网络代理？是不是tun模式的？感觉是我代码没考虑开代理的锅😕

**Comment by FujinomiyaNeko981213** [comment]
1.在用的时候发现解析我的RSS里面不存在东西，浏览器打开看了是可以的，然后一层层debug到这发现是当list里面的第一个名字就是不匹配正则的时候，match_result会一直是false，然后找不到任何相关的东西（当然也可以是我配置错误了。。总之改成这样之后解决了，进入下一个问题）
2.对的，我查阅了一下，因为直连现在是无法打开mikan的RSS的，所以我开了代理，然后代理服务器只能支持http不能支持https之类的导致的握手失败，最接近的原因我找到的是https://www.cnblogs.com/davyyy/p/14388623.html
然后我参照上述链接的方法看了下，也还是有问题，另外我没有用tun模式

**Comment by TwooSix** [comment]
> 1.在用的时候发现解析我的RSS里面不存在东西，浏览器打开看了是可以的，然后一层层debug到这发现是当list里面的第一个名字就是不匹配正则的时候，match_result会一直是false，然后找不到任何相关的东西（当然也可以是我配置错误了。。总之改成这样之后解决了，进入下一个问题） 2.对的，我查阅了一下，因为直连现在是无法打开mikan的RSS的，所以我开了代理，然后代理服务器只能支持http不能支持https之类的导致的握手失败，最接近的原因我找到的是https://www.cnblogs.com/davyyy/p/14388623.html 然后我参照上述链接的方法看了下，也还是有问题，另外我没有用tun模式

1. 确实有这个问题，因为正则在后续更换为蜜柑的订阅链接后感觉不太实用，缺乏了debug，有点遗留问题，感谢修正！
2. 可以尝试在`core/mikan.py`中的`__parse_anime_name`函数内指定使用代理看看能不能解决问题。具体修改后代码如下：
```python
    def __parse_anime_name(self, feed_entry) -> str:
        try:
            home_page_url = feed_entry.link
            # craw the anime name from homepage
            proxies = {
                "http": "http://127.0.0.1:10809", # 端口更改为你的代理端口
                "https": "http://127.0.0.1:10809",
            }
            resp = requests.get(home_page_url, proxies=proxies)
            soup = bs4.BeautifulSoup(resp.text, "html.parser")
            anime_name = soup.find("p", class_="bangumi-title").text.strip()
            # try to fix memory leak caused by BeautifulSoup
            resp.close()
            soup.decompose()
            soup = None
            gc.collect()
        except Exception as e:
            logger.error(f"Error when get anime name:\n{e}")
            return None
        return anime_name
```
（如果软件支持tun模式的话，使用tun应该也可以解决问题）

**Comment by FujinomiyaNeko981213** [comment]
谢谢您这么快的回复我！
我尝试了您上述的两种方式，TUN模式和手动指定proxy，都还是会抛出
HTTPSConnectionPool(host='mikanani.me', port=443): Max retries exceeded with url: /Home/Episode/569378ba7478a565278f7ac9cc3b73977c8d539d (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
这个错误，我明天再看看还有什么替代方式吧，谢谢你！

**Comment by TwooSix** [comment]
> 谢谢您这么快的回复我！ 我尝试了您上述的两种方式，TUN模式和手动指定proxy，都还是会抛出 HTTPSConnectionPool(host='mikanani.me', port=443): Max retries exceeded with url: /Home/Episode/569378ba7478a565278f7ac9cc3b73977c8d539d (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))) 这个错误，我明天再看看还有什么替代方式吧，谢谢你！

很抱歉没有能够帮你解决问题:(
我这边没能复现你的问题，可能需要更多的信息来帮助复现。

**Comment by FujinomiyaNeko981213** [comment]
我使用的代理软件是clash，版本是V0.19.12
![image](https://github.com/TwooSix/Alist-MikananiRss/assets/31889953/1a5c91ec-0802-4afc-b319-45d13821afa4)
其他的配置如图，我正在尝试更新clash看是否能帮助解决问题

**Comment by FujinomiyaNeko981213** [comment]
![image](https://github.com/TwooSix/Alist-MikananiRss/assets/31889953/8e95c32f-0a65-4f40-b247-43eee6cdb140)
its work!

**Comment by TwooSix** [comment]
恭喜！
所以只是单纯的clash的问题吗？关闭tun模式，代码内不指定proxies是否能够正常执行？

**Comment by FujinomiyaNeko981213** [comment]
您好！无论开或者不开tun模式，只要指定proxies就能正常执行到解析名字这一步
偶尔会出现远程服务器拒绝请求，不能稳定复现，有稳定复现例子我再跟您沟通

**Comment by TwooSix** [comment]
> 您好！无论开或者不开tun模式，只要指定proxies就能正常执行到解析名字这一步 偶尔会出现远程服务器拒绝请求，不能稳定复现，有稳定复现例子我再跟您沟通

非常感谢你的反馈，后续有空我会加上代理的配置，403拒绝请求的话应该就是访问频率太高的原因了，后续会在爬番剧名字那块加点睡眠时间，我先reopen一下issue
