### ISSUE TITLE
aria2下载的种子重命名问题

### ISSUE THREAD

**Issue by hui-ld** [TwooSix/Alist-MikananiRss#23]
首先感谢佬写的程序
我使用docker alist-aria2整合镜像
aria2会将种子下载下来并且一并上传，触发重命名规则的也是种子文件
如图：
![image](https://github.com/TwooSix/Alist-MikananiRss/assets/112241195/ed53b49f-8253-458c-8f03-a0cd0077ee81)
如果可以这个种子文件可以下载之后删除？或者重命名规则检测到.torrent后缀不会触发？

**Comment by TwooSix** [comment]
目前的逻辑是选择下载完成后第一个创建的上传任务作为重命名对象，有点糙，后续有空加个文件名后缀判断吧。
至于下载后删除torrent文件我记得aria2可以自行写个脚本什么的配置的。
