### ISSUE TITLE
下载进度卡在100%，网盘只有aria2文件

### ISSUE THREAD

**Issue by ChricLu** [TwooSix/Alist-MikananiRss#26]
下载进度卡在100%，一直在做种，一直在“正在下载”列表中。网盘中只有aria2文件和种子文件，本地电脑中aria2临时文件夹里却有下载完成的文件。Alist控制台报错，请问怎么解决？

![01](https://github.com/TwooSix/Alist-MikananiRss/assets/17893450/8dc24d35-865a-4ec1-8683-e1bb49044c3a)
![02](https://github.com/TwooSix/Alist-MikananiRss/assets/17893450/6e2791fa-7376-4758-bd46-a1282b3423b0)
![03](https://github.com/TwooSix/Alist-MikananiRss/assets/17893450/3e74895f-d744-4694-85a2-93540f693d09)
![微信截图_20240624132156](https://github.com/TwooSix/Alist-MikananiRss/assets/17893450/ef7df18f-e3c5-4c76-adc6-ce9c5fb8a1fb)
![04](https://github.com/TwooSix/Alist-MikananiRss/assets/17893450/90509930-12a6-4fa5-9682-fb84a2c5a3e6)
![05](https://github.com/TwooSix/Alist-MikananiRss/assets/17893450/dbb37a60-b06b-4c5d-b88d-a12323a335d5)

**Comment by ChricLu** [comment]
补一张这个项目的控制台报错信息
![1](https://github.com/TwooSix/Alist-MikananiRss/assets/17893450/9e562433-12b7-4fc9-983f-436354a78a8b)

**Comment by TwooSix** [comment]
看起来是aria2下载完成后，在上传到网盘这一步时报错了，请检查是否存在网络问题。此外，这个问题主要由于alist那边无法正常创建上传任务，导致这边运行异常，建议是到alist那边开issue
