### ISSUE TITLE
请问可以添加其他RSS的支持或者多个RSS吗？

### ISSUE THREAD

**Issue by Rlezzo** [TwooSix/Alist-MikananiRss#30]
我想用动漫花园的RSS或者dandanplay的RSS，好像区别就是enclosure的url蜜柑是种子下载地址，前者的是磁链？还有可以添加多个RSS吗？

**Comment by TwooSix** [comment]
1. 主要是蜜柑有稳定且格式统一的番剧名，这项目会对种子按照番剧分文件夹归类，重命名部分也依赖了这个稳定的番剧名信息，其他网站个人不太常用，但之前了解了一下基本也只能获取到资源名信息，单纯利用各字幕组的资源名提取稳定的番剧名，个人目前有技术实现上的困难，最近也比较忙，如果要使用其他RSS，可能要放弃绝大部分的功能，变成纯粹的RSS->Alist的爬虫，后面有空可能会稍微重构一下，改成插件式设计再考虑要不要作其他RSS。
2. 多RSS有计划支持

**Comment by Rlezzo** [comment]
感谢回复，那如果我手动往qBittorrent添加RSS，然后利用您的alist文件夹里的离线上传，可以临时实现其他RSS源的alist离线下载吗？

**Comment by TwooSix** [comment]
> 感谢回复，那如果我手动往qBittorrent添加RSS，然后利用您的alist文件夹里的离线上传，可以临时实现其他RSS源的alist离线下载吗？

qBittorrent直接添加的话，似乎和alist本身没有联动，你可能需要自己监视是否有文件下载再上传。alist文件夹里是我自己抓的一套alist api，可以直接使用，如果会python，要自己实现的话，我建议的一个最简单的方案是：定期调用feedparser库解析rss，提取种子链接，用alist类中的add_offline_download_task添加下载任务，然后自己简单的对已下载过的资源作一下标记即可，我这里是用数据库。

**Comment by Rlezzo** [comment]
好的，非常感谢！

**Comment by TwooSix** [comment]
新的代码已经重构完了，也支持了多RSS，现在要支持自己想要的rss应该不会很难，实现可以参考[开发指南](https://github.com/TwooSix/Alist-MikananiRss/wiki/%E5%BC%80%E5%8F%91%E8%80%85%E6%8C%87%E5%8D%97)

**Comment by Rlezzo** [comment]
哇，这么快，我自己的才用几天，谢谢大佬
