### ISSUE TITLE
考虑支持docker部署吗

### ISSUE THREAD

**Issue by Katou-Kouseki** [TwooSix/Alist-MikananiRss#37]

**Comment by TwooSix** [comment]
可以考虑

**Comment by TwooSix** [comment]
文档：[使用docker](https://github.com/TwooSix/Alist-MikananiRss/wiki/%E4%BD%BF%E7%94%A8docker)
简单实现了一下，只做了linux平台的镜像构建
ca280cd

**Comment by Katou-Kouseki** [comment]
> 文档：[使用docker](https://github.com/TwooSix/Alist-MikananiRss/wiki/%E4%BD%BF%E7%94%A8docker) 简单实现了一下，只做了linux平台的镜像构建 [ca280cd](https://github.com/TwooSix/Alist-MikananiRss/commit/ca280cdc49069b4a1fcf0afbca2eb7c3d26dc023)

爱了爱了❤️
